name: Rahat Documentation CI/CD
on: [push]
jobs:
  build:
    name: Build & Deploy to Github Pages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }}
      - run: npm install
      - run: npm run build
      - name: Release to GitHub Pages
        env:
          USE_SSH: true
          GIT_USER: git
      - run: |
          git config --global user.email "esatya@rumsan.com"
          git config --global user.name "esatya"
          npm run deploy
